FROM python:3.11

WORKDIR /Api

COPY ./requirements.txt ./Api/requirements.txt

#RUN pip install -r ./requirements.txt

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "127.0.0.1", "--port", "8000"]

#CMD ["main:app", "--port", "8000"] 
#"uvicorn" lo acabo de quitar
#FROM python:3.11 
#FROM python : versión para determinar de dónde viene el servidor elegido
#WORKDIR C:\Users\violeta.macias\proyectos\Api
#WORKDIR / nombre de la carpeta este se usa para decir qué información tendrá dentro el contenedor cuando se inicia en el equipo
#COPY . Carpetadocker
#COPY . / nombre de la carpeta para copiar los elementos dentro de esa carpeta
#EXPOSE 8000
#EXPOSE+ puerto especificando el puerto que se usa
# Se debe especificar el entrypoint y el comando: ENTRYPOINT “[“npm”]” y CMD “[“start”]” respectivamente
# para descargas la imagen de python en docker: docker pull python:3.9.16-slim-bullseye
#CMD [ "python", "main.py" ]
#para crear la imagen:
#docker build -t imagdock . -f DockerFile
#para crear el contenedor:
#puse esto:
#docker run -d --name appython4 -p 8000:8000 imagdock3
#no funciona el comando de creacioon de docker 
#Mirar esto: https://stackoverflow.com/questions/72235848/starting-container-process-caused-exec-uvicorn-executable-file-not-found-in?rq=1
#docker run -p 8080:8080 -d <your-username>/node-app-name
#docker build . -t imagdock

