###FROM imagen de python:
FROM python:3.11 
###COPY x y: copia x archivo al contenedor y renombra con el nombre de y 
COPY . /Api
#COPY . .
#COPY ./requirements.txt /Api/requirements.txt

###EXPOSE puerto
EXPOSE 8000
WORKDIR /Api

###ENTRYPOINT es el comando que define que archivos 
#se ejecutarán cuando se inicie el contenedor
#ENV APP=main:app
###RUN construir applicación
#RUN pip install -r ./requirements.txt
RUN pip install -r /Api/requirements.txt
CMD ["/usr/local/bin/uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
#ENV PATH=/home/violeta.macias/.local/bin:${PATH}
#CMD ["python", "main.py"]
#C:\Users\violeta.macias\proyectos\Api
#CMD ["main:app", "--port", "8000"] 
#"uvicorn" lo acabo de quitar
#FROM python:3.11 
#FROM python : versión para determinar de dónde viene el servidor elegido
#WORKDIR C:\Users\violeta.macias\proyectos\Api
#WORKDIR / nombre de la carpeta este se usa para decir qué información tendrá dentro el contenedor cuando se inicia en el equipo
#COPY . Carpetadocker
#COPY . / nombre de la carpeta para copiar los elementos dentro de esa carpeta
#EXPOSE 8000
#EXPOSE + puerto especificando el puerto que se usa
# Se debe especificar el entrypoint y el comando: ENTRYPOINT “[“npm”]” y CMD “[“start”]” respectivamente
# para descargas la imagen de python en docker: docker pull python:3.9.16-slim-bullseye
#CMD [ "python", "main.py" ]

#para crear la imagen:
#docker build -t imagdock . -f DockerFile
#para crear el contenedor:
#puse esto:
#docker run -d --name appython -p 8000:8000 imagdock
#docker run -d --name appython -it -p 8000:8000 imagdock

